import Head from "next/head";
import Image from "next/image";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import React from "react";
import styled from "styled-components";

import NavBar from "@/components/NavBar";

// const inter = Inter({ subsets: ["latin"] });

const Home = () =>  {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <MainContainer>
        
      <TitleBanner>Welcome to BlockSwap</TitleBanner>
      <DescriptionText>
        Join the emergeing movement of DeFi now!
        Access thousands of tokens and vote, all from your coin wallet.


      </DescriptionText>

      </MainContainer>

    </>
  );
}


const MainContainer = styled.div`
width: 100%;
height: 100vh;

display: flex;
flex-direction: column;
font-size: 1rem;
align-items: center; // this one controls the vertical alignment
justify-content: center; // this one controls the horizontal alignment
// align with space between
color: white;
background-color: rgba(17, 24, 39);
`;
const TitleBanner = styled.div`
font-size: 2rem;
`;

const DescriptionText = styled.div`


`;

export default Home;